### ISSUE TITLE
Update metadata, favicon, chat, & apply analytics

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/tf-support-live#3]
Once we get the gridsome setup, there are three more items:

1. Currently the metadata talks about pingendo, which obviously will be changed when we go to Gridsome, but let's make the metadata: ThreeFold Support | Reach us for support via live chat!
2. Let's update the favicon to the ThreeFold logo
3. Add live chat 
4. Let's apply Matomo Analytics

**Comment by Vilnite** [comment]
Live chat added
Tab updated with ThreeFold (favicon)

**Comment by Vilnite** [comment]
Please link Chat Now button to live chat on the bottom right corner:

<img width="1363" alt="Screenshot 2021-02-03 at 13 37 04" src="https://user-images.githubusercontent.com/20182572/106742202-60df4480-6625-11eb-88de-8f2cd3139967.png">

**Comment by samaradel** [comment]
> Please link Chat Now button to live chat on the bottom right corner:
> 
> <img alt="Screenshot 2021-02-03 at 13 37 04" width="1363" src="https://user-images.githubusercontent.com/20182572/106742202-60df4480-6625-11eb-88de-8f2cd3139967.png">

Fixed

**Comment by Vilnite** [comment]
Have we applied Matomo and updated meta data?

**Comment by samaradel** [comment]
> Have we applied Matomo and updated meta data?

Done
